#!/bin/bash

# Clean previous build files
rm -rf autom4te.cache
rm -f aclocal.m4 ltmain.sh config.h.in

# Generate configuration scripts
aclocal
autoconf
autoheader
automake --add-missing --foreign

echo "Bootstrap complete. Now you can run './configure'."
